### ISSUE TITLE
Additional lines in Makefile

### ISSUE THREAD

**Issue by jarad** [wlandau/workflowHelper#2]
How would a user insert additional lines into the Makefile? Obviously, they can create the Makefile and then manually edit, but it would be preferable to be able to provide it within the script. In particular, I would like to be able to add the following to the beginning of the Makefile

    SHELL=srun
    .SHELLFLAGS= -N1 -n1  bash -c

Possible solutions are 

- Add an argument in `plan_workflow` that allows you to add to the beginning of the file. 
- Add `append` argument to `plan_workflow` so that you can write to the Makefile first and then append using `plan_workflow`. 
- Add `...` argument to `plan_workflow` that gets passed to `sink` allowing you to use `append` and any other argument in `sink`.

**Comment by wlandau** [comment]
Done. There is now a `begin` argument to `plan_workflow`. See the updated example and its README.md. I prefer prepending rather than appending, it seems like the custom parts should come before the automatic parts.

**Comment by jarad** [comment]
To be clear, I agree that custom parts should come first, but all solutions provided this effect. The latter two allow you to write multiple times to the Makefile on your own **before** using `plan_workflow`. The `begin` solution forces the user to put all the custom parts into a single character variable, which may not be the best coding approach. 

Also, why a character vector rather than just a scalar character which may have `\n` and thus cause newlines in the result custom material?

**Comment by wlandau** [comment]
Ah, now I understand what you meant by appending. I actually like the current behavior, which is to create/overwrite. For one, the user can't add targets with a text editor beforehand, so reproducibility is more easily assured. Also, if appending were available, I would probably make the mistake of calling `plan_workflow` twice, causing duplicated targets and thus errors in the `Makefile`. In that sense, I find it convenient that `plan_workflow` is guaranteed to refresh/reset the commands rather than appending to things.

Also, `plan_workflow(begin = c("# This is my Makefile", "# Variables..."))` is equivalent to `plan_workflow(begin = "# This is my Makefile\n# Variables...")`, so you're still free to use a single string with newline characters. I wanted to allow for both possibilities without assuming that the user knows what `\n` is.

**Comment by jarad** [comment]
Both are good points.
