### ISSUE TITLE
Non-function dependencies

### ISSUE THREAD

**Issue by jarad** [wlandau/workflowHelper#5]
Suppose my function `f` depends on a textfile `foo.txt`, is there a way to properly assign dependencies so that any changes in `foo.txt` will trigger rebuilds for downstream targets that depend on `f`?

The particular scenario I am imagining is running analyses with Stan where the Stan model is defined in a file and then there is a function that reads the file.

**Comment by wlandau** [comment]
Remake takes care of this automatically as long as the literal "foo.txt" is an explicit argument of a command. I would do something like analyses = commands(f("foo.txt", ...)). Because of the file extension, remake will assume it's an external file and a dependency, and changes to the contents of foo.txt trigger downstream rebuilds. To pass a string literal that is not a dependency, use I(), as in analyses = commands(f(I("foo.txt", ...))). Playing with the example in the readme of remake should also help.
